export default {
  plugins: {
    'postcss-import': {},
    'tailwindcss/nesting': 'postcss-nesting',
    tailwindcss: {},
    'postcss-preset-env': {
      stage: 3,
      features: {
        'nesting-rules': true,
        'custom-properties': true,
        'custom-media-queries': true,
        'custom-selectors': true,
        'is-pseudo-class': true,
        'focus-visible-pseudo-class': true,
        'focus-within-pseudo-class': true,
        'color-functional-notation': true,
        'cascade-layers': true,
        'logical-properties-and-values': true,
        'prefers-color-scheme-query': true,
        'gap-properties': true,
        'overflow-wrap-property': true,
        'place-properties': true,
        'hexadecimal-alpha-notation': true,
      },
      autoprefixer: {
        flexbox: 'no-2009',
        grid: 'autoplace',
      },
    },
    ...(process.env.NODE_ENV === 'production' ? {
      cssnano: {
        preset: [
          'advanced',
          {
            discardComments: {
              removeAll: true,
            },
            reduceIdents: true,
            mergeIdents: true,
            mergeRules: true,
            minifyFontValues: true,
            minifyParams: true,
            minifySelectors: true,
            normalizeCharset: true,
            normalizeDisplayValues: true,
            normalizePositions: true,
            normalizeRepeatStyle: true,
            normalizeString: true,
            normalizeTimingFunctions: true,
            normalizeUnicode: true,
            normalizeUrl: true,
            normalizeWhitespace: true,
            orderedValues: true,
            uniqueSelectors: true,
            discardDuplicates: true,
            discardOverridden: true,
            discardUnused: true,
            mergeRules: true,
            reduceTransforms: true,
            svgo: true,
            zindex: false,
            cssDeclarationSorter: {
              order: 'smacss',
            },
          },
        ],
      },
      'postcss-purgecss': {
        content: [
          './index.html',
          './src/**/*.{js,jsx,ts,tsx}',
        ],
        defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: {
          standard: [
            /^swiper/,
            /^aos/,
            /^animate/,
            /^transition/,
            /^transform/,
            /^scale/,
            /^rotate/,
            /^translate/,
            /^opacity/,
            /^shadow/,
            /^blur/,
            /^grayscale/,
            /^brightness/,
            /^contrast/,
            /^hue-rotate/,
            /^invert/,
            /^saturate/,
            /^sepia/,
            /^backdrop/,
            /^placeholder/,
          ],
          deep: [
            /^dg-/,
            /disabled$/,
            /active$/,
            /focus$/,
            /hover$/,
            /group-hover$/,
          ],
          greedy: [
            /^(.*)?:disabled$/,
            /^(.*)?:active$/,
            /^(.*)?:focus$/,
            /^(.*)?:hover$/,
            /^(.*)?:focus-within$/,
            /^(.*)?:focus-visible$/,
          ],
        },
        variables: true,
        keyframes: true,
        fontFace: true,
      },
      'postcss-combine-duplicated-selectors': {
        removeDuplicatedProperties: true,
        removeDuplicatedValues: true,
      },
      'postcss-sort-media-queries': {
        sort: 'mobile-first',
      },
    } : {}),
  },
}
